### ISSUE TITLE
[Bug]: Unsupported protocol version: 19968

### ISSUE THREAD

**Issue by YOMO-Lee** [oceanbase/oblogclient#82]
### Describe the bug

当我使用OB-CDC的时候，是可以通过OBLogProxy结合OBLogClient使用，但是现在报错如下
```
com.oceanbase.clogproxy.client.exception.LogProxyClientException: Unsupported protocol version: 19968
	at com.oceanbase.clogproxy.client.connection.ClientHandler.checkHeader(ClientHandler.java:276) ~[oblogclient-logproxy-1.1.1.jar:?]
	at com.oceanbase.clogproxy.client.connection.ClientHandler.handleHeader(ClientHandler.java:193) ~[oblogclient-logproxy-1.1.1.jar:?]
	at com.oceanbase.clogproxy.client.connection.ClientHandler.channelRead(ClientHandler.java:160) ~[oblogclient-logproxy-1.1.1.jar:?]
```
![c97cbdde5848c784e11c012f4b957a2](https://github.com/user-attachments/assets/3af4dcdd-02b4-4a68-b057-5a90a87c3eb9)

请问如何处理呢

### Environment

OceanBase：4.2.1
OBProxy：4.2.1
OBLogClient：1.1.3
OBLogProxy：4.0.1

### Fast reproduce steps

![image](https://github.com/user-attachments/assets/a12de691-5868-4eef-9546-0649656eccab)

**Comment by whhe** [comment]
你用的是cdc模式吗，binlog模式对接的是mysql的binlog工具，oblogclient是用不了的

**Comment by YOMO-Lee** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
